Fix ENS name support
darwinia-network/collator-staking-ui-v2 pull request #33
Opened 2024-12-06 08:14 UTC by hamidroohi92

This PR close issue #31

2024-12-11 03:13 UTC, boundless-forest commented
Any updates on this? Please resolve the error reported by Vercel CI. @hamidroohi92

2024-12-11 08:37 UTC, hamidroohi92 commented
The issue resolved

2025-01-15 11:26 UTC, hackfisher requested changes
![IMAGE 2025-01-15 19:26:48](https://github.com/user-attachments/assets/6cdf6be5-4985-4190-9765-a5b5888a865e)

2025-01-24 00:28 UTC, hackfisher reviewed
<img width="642" alt="image" src="https://github.com/user-attachments/assets/6d27758e-e024-45d5-b8fa-fdae996231d6" />

2025-01-24 06:12 UTC, hackfisher approved these changes

2025-01-24 06:12 UTC, merged